import { Trait } from './types';

export interface ConditionDetails {
    type: 'Injury' | 'Acute' | 'Chronic';
    // Average number of turns to recover. A turn is 1-2 years. 1 means it recovers in the next turn.
    recoveryTurns: number; 
    sequelae?: { // Potential long-term effects
        trait: Trait;
        chance: number; // 0 to 1
    };
}

export const HEALTH_CONDITIONS: Record<string, ConditionDetails> = {
    'Perna Quebrada': { type: 'Injury', recoveryTurns: 1, sequelae: { trait: { name: 'Mancar Permanente', description: 'Uma antiga lesão nunca sarou completamente, afetando sua mobilidade.', type: 'negative' }, chance: 0.3 } },
    'Braço Quebrado': { type: 'Injury', recoveryTurns: 1, sequelae: { trait: { name: 'Dores no Braço', description: 'Seu braço dói em dias frios.', type: 'negative' }, chance: 0.2 } },
    'Gripe Forte': { type: 'Acute', recoveryTurns: 1 },
    'Pneumonia': { type: 'Acute', recoveryTurns: 1, sequelae: { trait: { name: 'Pulmões Frágeis', description: 'Você fica sem fôlego facilmente desde aquela doença.', type: 'negative' }, chance: 0.2 } },
    'Concussão': { type: 'Injury', recoveryTurns: 1, sequelae: { trait: { name: 'Dores de Cabeça Crônicas', description: 'Você sofre de dores de cabeça frequentes desde o acidente.', type: 'negative' }, chance: 0.4 } },
    'Esgotamento': { type: 'Acute', recoveryTurns: 1 },
    'Depressão': { type: 'Chronic', recoveryTurns: Infinity },
    'Ansiedade Generalizada': { type: 'Chronic', recoveryTurns: Infinity },
    'Asma': { type: 'Chronic', recoveryTurns: Infinity },
    'Câncer em Tratamento': { type: 'Chronic', recoveryTurns: Infinity },
    'Câncer em Remissão': { type: 'Chronic', recoveryTurns: Infinity },
};


export const BIRTHPLACES: string[] = [
    'A efervescente zona sul do Rio de Janeiro, a poucos passos da praia de Ipanema',
    'As favelas vibrantes do Rio de Janeiro',
    'Em um apartamento antigo no bairro da Liberdade, centro de São Paulo, com cheiros orientais e tradições vivas',
    'Em um assentamento rural no interior do Maranhão, com festa de São João e folguedo',
    'Em um bairro de classe média da Cidade do México, onde as festas são coloridas e barulhentas',
    'Em um bairro luxuoso de Dubai, Emirados Árabes, cercado por arranha-céus e supercarros',
    'Em um bairro operário do Porto, Portugal, entre fábricas e cafés tradicionais',
    'Em um conjunto habitacional na periferia da zona leste de São Paulo, pulsando com diversidade e luta',
    'Em um moderno condomínio de Bogotá, Colômbia, cercado por montanhas',
    'Em um recanto escondido na Chapada Diamantina, Bahia, entregue à natureza',
    'Em uma cidade dormitório ao redor de Paris, França, onde a multiculturalidade se encontra',
    'Em uma comunidade quilombola no interior do Espírito Santo, resgatando tradições ancestrais',
    'Em uma fazenda nos pampas gaúchos, entre chimarrão, gado e horizontes sem fim',
    'Em uma floresta tropical no Equador, próximo a povos indígenas e rios misteriosos',
    'Em uma vila nas montanhas geladas do interior da Noruega, com casinhas de madeira coloridas',
    'Entre as dunas do Saara, em um acampamento de nômades tuaregues',
    'Luanda, Angola',
    'Maputo, Moçambique',
    'Na ilha de Fernando de Noronha, um paraíso de praias e vida marinha exuberante',
    'Na zona rural de Goiás, onde o cerrado é retorcido e o céu é infinito',
    'Nas dunas quentes do sertão nordestino, em uma vila pacata e cheia de histórias',
    'Nas florestas geladas do sul do Canadá, próximo a um lago cristalino',
    'No balneário de Camboriú, Santa Catarina, com arranha-céus à beira da praia',
    'No Centro Histórico de Salvador, Bahia, onde os tambores ecoam e a fé movimenta multidões',
    'No centro antigo de Roma, Itália, entre ruínas históricas e o aroma de café',
    'No centro caótico de Nova York, EUA, onde todos estão sempre correndo',
    'No centro histórico de Lisboa, entre ruas de pedra e azulejos coloridos',
    'No centro tecnológico de Bangalore, Índia, onde modernidade e tradição se misturam',
    'No coração agrícola da Ucrânia, cercado por campos de trigo dourado',
    'No coração boêmio da Lapa, Rio de Janeiro, entre arcos, samba e boemia',
    'No litoral agitado de Natal, Rio Grande do Norte, entre dunas e praias',
    'No sertão cearense, entre mandacarus, vaqueiros e canções de aboio',
    'No sertão seco do Piauí, em um casebre simples e resistente',
    'Nos alpes suíços, em uma vila cercada por neve e chalés de madeira',
    'Nos arranha-céus e avenidas luminosas de Tóquio, Japão, sob o néon constante',
    'Nos becos vibrantes de Marrakech, Marrocos, entre mercados de especiarias e tapetes',
    'Nos canais e pontes de Amsterdã, Países Baixos, cercado por bicicletas e flores',
    'Nos docks industriais de Liverpool, Inglaterra, entre pubs e lendas dos Beatles',
    'Num povoado remoto do interior do Senegal, envolto por calor e hospitalidade',
    'Numa cidadezinha costeira de Alagoas, com jangadas e festas do mar',
    'Numa vila de pescadores do interior do Vietnã, entre arrozais e montanhas verdes',
    'Num vilarejo gelado da Sibéria, Rússia, onde o inverno é praticamente eterno',
    'O bucólico interior de Minas Gerais, cercado por montanhas e fazendas centenárias',
    'O centro histórico de Roma, Itália',
    'O coração financeiro de Londres, Reino Unido',
    'O coração financeiro de Londres, Reino Unido, em meio a arranha-céus e tradição',
    'O sertão do Nordeste, em uma vila pacata',
    'Os bairros boêmios de Buenos Aires, Argentina, onde o tango embala corações apaixonados',
    'São Paulo, Brasil',
    'Um bairro artístico em Buenos Aires, Argentina',
    'Um bairro boêmio em Paris, França',
    'Um bairro histórico de Havana, Cuba, embalado pelo som do son e do mar',
    'Um bairro histórico em Salvador, Bahia',
    'Um bairro operário de Detroit, EUA',
    'Um bairro rico e elitista de Dubai',
    'Um campo aberto na estepe mongol',
    'Um campo de refugiados na fronteira da Síria',
    'Um distrito colonial em Havana, Cuba',
    'Um distrito industrial em Contagem, Minas Gerais, rodeado por fábricas e gente batalhadora',
    'Um distrito tecnológico em Shenzhen, China',
    'Um kibutz no deserto de Israel',
    'Um monastério tibetano escondido no Himalaia',
    'Um subúrbio industrial decadente na Rússia',
    'Um subúrbio tranquilo em Brasília',
    'Um subúrbio tranquilo na zona oeste de Brasília, onde as ruas são largas e as árvores dominam a paisagem',
    'Um vilarejo congelado na Groenlândia',
    'Um vilarejo de caçadores no Alasca',
    'Um vilarejo de pescadores no litoral de Moçambique',
    'Um vilarejo medieval preservado na Alemanha',
    'Uma aldeia indígena isolada na Amazônia, cercada por rios, lendas e a floresta ancestral',
    'Uma aldeia maori na Nova Zelândia',
    'Uma aldeia remota nas montanhas de Angola',
    'Uma cabana isolada nas montanhas dos Andes',
    'Uma cidade histórica em Ouro Preto, Brasil',
    'Uma cidade portuária em Moçambique',
    'Uma cidade portuária movimentada na Nigéria',
    'Uma cidade universitária em Coimbra, Portugal',
    'Uma comuna artística em Berlim, Alemanha',
    'Uma comunidade agrícola no Rio Grande do Sul',
    'Uma comunidade espiritual nos Andes',
    'Uma comunidade quilombola no interior da Bahia',
    'Uma comunidade ribeirinha na Amazônia',
    'Uma comunidade ribeirinha do Pará, onde o barco é meio de transporte e sustento',
    'Uma ecovila autossustentável',
    'Uma estação de pesquisa na Antártida',
    'Uma fazenda de arroz no interior do Vietnã',
    'Uma fazenda de gado no interior do Texas',
    'Uma metrópole futurista em Tóquio, Japão',
    'Uma pacata vila pesqueira na costa de Portugal, de frente pro Atlântico selvagem',
    'Uma pequena cidade no interior de Portugal',
    'Uma pequena favela na zona norte do Recife, com festas juninas e céu colorido de pipas',
    'Uma pequena ilha no Caribe, dependente do turismo',
    'Uma reserva isolada na Amazônia',
    'Uma vila mineradora no interior da Austrália, cercada de deserto',
    'a agitada cidade de Nova Iorque, EUA',
    'a movimentada capital de Lisboa',
    'um bairro boêmio em Buenos Aires, Argentina',
    'uma favela no Rio de Janeiro',
    'uma vila de pescadores na Bahia',
];
